# Generated by Django 2.2.1 on 2019-05-26 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Professor Name', max_length=100, verbose_name='Name')),
                ('email', models.CharField(help_text='Professor email', max_length=100, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Professor',
                'verbose_name_plural': 'Professors',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('code', models.CharField(help_text='Subject Code', max_length=15, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(help_text='Subject Name', max_length=50, verbose_name='Name')),
                ('professor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='api.Professor')),
            ],
            options={
                'verbose_name': 'Subject',
                'verbose_name_plural': 'Subjects',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('code', models.CharField(help_text='Student Code', max_length=15, primary_key=True, serialize=False, verbose_name='Code')),
                ('name', models.CharField(help_text='Student Name', max_length=100, verbose_name='Name')),
                ('ira', models.FloatField(help_text='Student academic performance Index', verbose_name='IRA')),
                ('grade', models.FloatField(help_text='Student grade on the tutor selection process', verbose_name='Grade')),
                ('mention', models.CharField(help_text='Student Mention in the subject', max_length=2, verbose_name='Mention')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutors', to='api.Subject')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
            },
        ),
    ]
