# Generated by Django 2.2.1 on 2019-06-16 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='code',
        ),
    ]
