# Generated by Django 2.2.1 on 2019-06-16 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_student_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(help_text='Student Email', max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mention',
            field=models.CharField(help_text='Student Mention in the subject', max_length=255, verbose_name='Mention'),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='Student Name', max_length=255, verbose_name='Name'),
        ),
    ]
