# Generated by Django 2.2.1 on 2019-06-14 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='class_code',
            field=models.CharField(help_text='Class Code', max_length=10, verbose_name='Class Code'),
        ),
    ]
