# Generated by Django 2.2.1 on 2019-06-16 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190616_2348'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_code',
            field=models.CharField(default=None, help_text='Student Code', max_length=255, verbose_name='Code'),
            preserve_default=False,
        ),
    ]
