# Generated by Django 2.2.1 on 2019-06-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190616_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(help_text='Student Name', max_length=150, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_code',
            field=models.CharField(help_text='Student Code', max_length=15, null=True, verbose_name='Code'),
        ),
    ]
