# Generated by Django 2.2.1 on 2019-06-17 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20190617_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='email',
            field=models.CharField(help_text='Student Email', max_length=100, null=True, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='student',
            name='mention',
            field=models.CharField(help_text='Student Mention in the subject', max_length=2, null=True, verbose_name='Mention'),
        ),
    ]
