# Generated by Django 2.2.1 on 2019-06-17 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190617_0119'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='classcode',
            field=models.CharField(default=None, help_text='Class Code', max_length=2, null=True, verbose_name='Class Code'),
        ),
    ]
