# Generated by Django 2.2.1 on 2019-06-17 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_subject_classcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='classcode',
            field=models.CharField(default=None, help_text='Class Code', max_length=5, null=True, verbose_name='Class Code'),
        ),
    ]
