# Generated by Django 2.2.1 on 2019-05-29 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20190529_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='extension',
            field=models.CharField(default=None, max_length=4, null=True),
        ),
    ]
